"""Adding the email_verified column to members table

Revision ID: 441f9ea7de18
Revises: d2bf04532ded
Create Date: 2026-03-15 16:05:33.348667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '441f9ea7de18'
down_revision = 'd2bf04532ded'
branch_labels = None
depends_on = None


def upgrade():

    op.execute(
        "UPDATE fines SET reason = 'Not specified' WHERE reason IS NULL"
    )

    with op.batch_alter_table('fines') as batch_op:
        batch_op.alter_column(
            'reason',
            existing_type=sa.VARCHAR(),
            nullable=False
        )

    with op.batch_alter_table('members') as batch_op:
        batch_op.add_column(
            sa.Column(
                'email_verified',
                sa.Boolean(),
                nullable=False,
                server_default=sa.text('false')
            )
        )

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.drop_column('email_verified')

    with op.batch_alter_table('fines', schema=None) as batch_op:
        batch_op.alter_column('reason',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###
