"""add status to fines

Revision ID: c18f2f58cd3a
Revises: d6aa819d82c9
Create Date: 2026-03-12 18:50:13.629764

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c18f2f58cd3a'
down_revision = 'd6aa819d82c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fines', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fines', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
