"""Adding the reason column in fines table

Revision ID: d2bf04532ded
Revises: 0d159aac0fd2
Create Date: 2026-03-15 14:27:52.576132

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2bf04532ded'
down_revision = '0d159aac0fd2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fines', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reason', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fines', schema=None) as batch_op:
        batch_op.drop_column('reason')

    # ### end Alembic commands ###
